### ISSUE TITLE
videos are missing in the data 

### ISSUE THREAD

**Issue by mpetris** [olafgrabienski/vega-fortext#5]
The data from the forTEXT API doesn't contain the videos. Probably because "Video" isn't a proper category.

**Comment by olafgrabienski** [comment]
You're right, "Video" isn't a proper category, it's a content type. That said, it should be possible to include the items of this content type in the API view.

However, I didn't include the "Video" content type so far, because I wasn't sure if video posts should be treated the same as other article categories in the main category "Ressourcen", namely "Textsammlungen" and "Tagsets". In my opinion, even if part of the "Ressourcen" menu item, Videos are a different thing, they are rather a service provided by the forTEXT team than a conceptual category of the subjects treated by the forTEXT project.

Let's ask the forTEXT team for feedback. (@mpetris Do you know of any team members with a Github account?)

**Comment by olafgrabienski** [comment]
The video posts are now in the API data.
